// Generated by CoffeeScript 1.6.3
window.onload = function() {
  var config, q;
  try {
    config = JSON.parse(localStorage.getItem("config"));
  } catch (_error) {}
  if (!config) {
    config = {};
  }
  if (config.hostname == null) {
    config.hostname = "localhost";
  }
  if (config.port == null) {
    config.port = 7776;
  }
  q = function(query) {
    return document.querySelector(query);
  };
  console.log(config);
  q("#hostname").value = config.hostname;
  q("#port").value = config.port;
  q("#target").value = config.target || '';
  return window.onbeforeunload = function() {
    var data, hostname, port, target;
    hostname = q("#hostname").value;
    port = parseInt(q("#port").value);
    target = q("#target").value;
    if ((hostname != null ? hostname.length : void 0) >= 4) {
      config.hostname = hostname;
    }
    if (typeof port === "number") {
      config.port = port;
    }
    config.target = target;
    localStorage.setItem("config", JSON.stringify(config));
    data = {
      update: {
        hostname: hostname,
        port: port
      }
    };
    return chrome.extension.sendRequest(data, function(ret) {
      return console.log(ret);
    });
  };
};

/*
//@ sourceMappingURL=config.map
*/
