// Generated by CoffeeScript 1.6.3
var config, connect, global, lastTime, openSocket, reload, time;

global = {
  hostname: "localhost",
  port: 7776,
  ws: void 0,
  status: true,
  target: 'localhost'
};

try {
  config = JSON.parse(localStorage.getItem("config"));
} catch (_error) {}

if (config == null) {
  config = {};
}

if (config.hostname != null) {
  global.hostname = config.hostname;
}

if (config.port != null) {
  global.port = config.port;
}

if (config.target != null) {
  global.target = config.target;
}

time = function() {
  return (new Date).getTime();
};

lastTime = time();

reload = function() {
  var newTime;
  newTime = time();
  if ((newTime - lastTime) > 1000) {
    lastTime = newTime;
    if (global.status === true) {
      console.log('target', global.target);
      return chrome.tabs.query({}, function(tabs) {
        return tabs.map(function(tab) {
          var ss;
          ss = global.target;
          if ((ss != null) && (tab.url.indexOf(ss) > 0)) {
            console.info('reloading', tab.url);
            return chrome.tabs.reload(tab.id);
          }
        });
      });
    } else {
      return console.info('status is off, will not reload');
    }
  } else {
    return console.warn('too frequent, not reload');
  }
};

openSocket = function() {
  var h, p;
  h = global.hostname;
  p = global.port;
  global.ws = new WebSocket("ws://" + h + ":" + p);
  global.ws.onmessage = function(message) {
    if (global.status) {
      return reload();
    } else {
      return console.info('disabled in status');
    }
  };
  global.ws.onclose = function() {
    delete global.ws.onclose;
    delete global.ws;
    console.log('connection closed, calling connect');
    return connect();
  };
  return global.ws.onopen = function() {
    return console.info('connection established');
  };
};

connect = function() {
  if (global.status === true) {
    if (global.ws) {
      return console.info('connected');
    } else {
      console.log("connecting...");
      return setTimeout(openSocket, 1000);
    }
  }
};

chrome.browserAction.onClicked.addListener(function(tab) {
  if (global.status === true) {
    console.info('status disabled');
    global.ws.close();
    chrome.browserAction.setIcon({
      path: "img/d-off.png"
    });
    return global.status = false;
  } else {
    chrome.browserAction.setIcon({
      path: "img/d-on.png"
    });
    global.status = true;
    console.info('status enabled, will call connect');
    return connect();
  }
});

chrome.extension.onRequest.addListener(function(req, sender, res) {
  var hostname, port, _ref, _ref1;
  _ref = req.update, hostname = _ref.hostname, port = _ref.port;
  global.hostname = hostname;
  global.port = port;
  return (_ref1 = global.ws) != null ? _ref1.close() : void 0;
});

chrome.browserAction.setIcon({
  path: "img/d-on.png"
});

console.clear();

console.log('starting data:', global);

connect();

/*
//@ sourceMappingURL=listen.map
*/
