// Generated by CoffeeScript 1.6.2
var connect, delay, global, reconnect, reload;

delay = function(t, f) {
  return setTimeout(f, t);
};

global = {
  hostname: "localhost",
  port: 7776,
  ws: void 0,
  status: true
};

connect = function() {
  var h, p;

  h = global.hostname;
  p = global.port;
  global.ws = new WebSocket("ws://" + h + ":" + p);
  global.ws.onmessage = function(message) {
    if (global.status === true) {
      if (message.data === 'reload') {
        return reload();
      }
    }
  };
  return global.ws.onclose = function() {
    global.ws = void 0;
    return console.log('closed');
  };
};

reload = function() {
  return chrome.tabs.getSelected(function(tab) {
    return chrome.tabs.reload(tab.id);
  });
};

(reconnect = function() {
  return delay(6000, function() {
    if ((!global.ws) && (global.status === true)) {
      return connect();
    }
  });
})();

chrome.browserAction.onClicked.addListener(function(tab) {
  console.log(tab);
  if (global.status === true) {
    chrome.browserAction.setIcon({
      path: "img/d-off.png"
    });
    return global.status = false;
  } else {
    chrome.browserAction.setIcon({
      path: "img/d-on.png"
    });
    return global.status = true;
  }
});
